export const config = {
  port: parseInt(Bun.env.GATEWAY_PORT || '4567'),
  gatewayToken: Bun.env.GATEWAY_TOKEN || '',
  gatewayTokenAlt: Bun.env.GATEWAY_TOKEN_ALT || '',
  deepseekKey: Bun.env.DEEPSEEK_API_KEY || '',
  openrouterKey: Bun.env.OPENROUTER_API_KEY || '',
  anthropicKey: Bun.env.ANTHROPIC_API_KEY || '',
  supabaseUrl: Bun.env.SUPABASE_URL || '',
  supabaseKey: Bun.env.SUPABASE_KEY || '',
  embeddingKey: Bun.env.EMBEDDING_API_KEY || '',
  treeChatKey: Bun.env.TREE_CHAT_KEY || '',
  treeApiKey: Bun.env.TREE_API_KEY || '',
  treeAwsKey: Bun.env.TREE_AWS_KEY || '',
  relayKey: Bun.env.RELAY_API_KEY || '',
  relayBase: Bun.env.RELAY_BASE_URL || 'https://crs.susumighostlily.uk/api/v1/messages',
  guaKey: Bun.env.GUA_API_KEY || '',
  guaBase: Bun.env.GUA_BASE_URL || 'https://woof.guagua.uk/v1/chat/completions',
  treeNewKey: Bun.env.TREE_NEW_API_KEY || '',
  treeNewBase: Bun.env.TREE_NEW_BASE_URL || 'https://api.treegpt.cc/v1/chat/completions',
  embeddingModel: Bun.env.EMBEDDING_MODEL || 'text-embedding-3-small',
  brainEnabled: Bun.env.BRAIN_ENABLED === 'true',
  embeddingBase: Bun.env.EMBEDDING_BASE_URL || 'https://api.openai.com/v1',
};
